### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by GinoPane** [nashby/povishaly-extension#1]
It looks like the extension broke:

![image](https://user-images.githubusercontent.com/3897579/158540513-7616360a-bebd-43e9-90c4-5be4bc4aee0b.png)

**Comment by nashby** [comment]
@GinoPane thanks for reporting. Extension works now for old ads but it's impossible to update data now since looks like onliner is blocking any outside BY traffic. Can't do much about it.
